#configmap to store env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: robomart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: robomart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robomart
      component: cart
      tier: backend
  template:
    metadata:
      labels:
        project: robomart
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: azharmd/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: robomart
spec:
  selector:
    project: robomart
    component: cart
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
#HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: robomart
  labels:
    project: robomart
    component: cart
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

