apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: robomart
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
#service
apiVersion: v1
kind: Service
metadata:
  name: mysql 
  namespace: robomart
spec:
  selector:
    project: robomart
    component: mysql 
    tier: db
  ports:
  - protocol: TCP 
    port: 3306 #service port
    targetPort: 3306 #container port
---
#headless service
apiVersion: v1
kind: Service
metadata:
  name: mysql-hl
  namespace: robomart
spec:
  clusterIP: None
  selector:
    project: robomart
    component: mysql 
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql 
  namespace: robomart
spec:
  selector:
    matchLabels:
      project: robomart
      component: mysql 
      tier: db
  serviceName: mysql-hl
  replicas: 1
  template:
    metadata:
      labels:
        project: robomart
        component: mysql 
        tier: db
    spec:
      containers:
      - name: mysql
        image: azharmd/mysql:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "robomart-ebs"
      resources:
        requests:
          storage: 1Gi


