#configmap to store env variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: robomart
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: robomart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robomart
      component: user
      tier: backend
  template:
    metadata:
      labels:
        project: robomart
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image: azharmd/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: robomart
spec:
  selector:
    project: robomart
    component: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
#HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: robomart
  labels:
    project: robomart
    component: user
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

